version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 1s
      timeout: 5s
      retries: 5
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - my_network

  django_backend:
    build:
      context: ./task-tracker-pet-project
    container_name: django_backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
    volumes:
      - static_volume:/app/static
    networks:
      - my_network
    depends_on:
      postgres:
        condition: service_healthy

  nginx:
    image: nginx:1.25.5-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - '80:80'
      - '444:443'
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl_certificates:/etc/letsencrypt/ssl_certificates
      - static_volume:/static
    networks:
      - my_network
    depends_on:
      - django_backend

volumes:
  pg_data:
  static_volume:

networks:
  my_network:
    driver: bridge